### ISSUE TITLE
Add PointsMaterialProps to iCSMAllProps type

### ISSUE THREAD

**Issue by dsa** [FarazzShaikh/THREE-CustomShaderMaterial#15]
Adapting your example here:
https://blog.farazshaikh.com/stories/rendering-1-m-particles/

But using TS + React Three Fiber and can't pass a `size` prop to `CustomShaderMaterial` without TS getting upset. 😞

**Comment by FarazzShaikh** [comment]
Hey! CSM’s API has been updated since that post. Can you share some code? Does your code work with ts-ignore?

**Comment by FarazzShaikh** [comment]
Closed via `v3.2.10`
