### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by badde-media** [FarazzShaikh/THREE-CustomShaderMaterial#16]
I've just thought about the possibility to extend the standard materials with custom shaders today, and then I stumbled upon this. Seems to be exactly what I've been thinking of, and seems to be well done. Unfortunately, the two external examples you have provided have some issues that prohibit them to work. Please check them.

**Comment by FarazzShaikh** [comment]
Thanks for checking this out!

What issues specifically? Can you attach a screenshot of the error? They seem to work fine for me online and locally

**Comment by FarazzShaikh** [comment]
Closing because I cannot repeoduce and lack of information. Re-open with more info if needed

**Comment by badde-media** [comment]
Sorry for the late reply. Both of the CodePen examples you have linked throw this error:
```
Error during service worker registration: s@https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:26314
../common/lib/registerServiceWorker.js/</t.default@https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:27283

./src/sandbox/index.ts/<@https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:323161
```
while showing just a plain white screen. Tested in Firefox. Just tested in Chrome, too, runs. Looks awesome. I realized that in FF, they both show the correct image for like a millisecond or so before turning white.

**Comment by FarazzShaikh** [comment]
Those errors seem to be unrelated to this library. They seem to come from codesandbox itself. I just tested on latest Firefox and they run great. 

![image](https://user-images.githubusercontent.com/55190601/163996538-7e1c9683-02ea-4466-8dcc-367cd5486eb8.png)
