### ISSUE TITLE
CSM doesn't source texture maps

### ISSUE THREAD

**Issue by hmans** [FarazzShaikh/THREE-CustomShaderMaterial#17]
When creating a CSM based off `MeshStandardMaterial` and assigning a `map` prop referencing a texture, the texture will only be used when _not_ passing a fragment shader chunk to the CSM, or passing a fragment shader chunk that doesn't have a `main` entrypoint. As soon as you pass a chunk with a `main`, the diffuse/fragment colors will always reset to red (or whatever color you end up setting yourself in the shader.)

Currently, you need to work around this by sourcing the texture yourself:

```glsl
void main() {
  csm_FragColor = texture2D(map, vUv);
}
```

**Comment by hmans** [comment]
Quickly updating this to mention that I was no longer able to reproduce this, so I'm self-closing it for now until I can.

**Comment by FarazzShaikh** [comment]
`3.4.0` should button this up even if its not fixed

**Comment by hmans** [comment]
Correction to my previous comment: I could reproduce it, the bug occurred when I had a _code comment_ that included the string `csm_DiffuseColor`. But since a fix is coming up, I will leave it closed. Thanks!
