### ISSUE TITLE
.clone() does not seem to copy shaders

### ISSUE THREAD

**Issue by hamzakubba** [FarazzShaikh/THREE-CustomShaderMaterial#20]
The material created by the .clone() function on CustomShaderMaterial instances seems to be missing shaders.

CSB available at https://codesandbox.io/s/transformcontrols-and-makedefault-forked-863utu?file=/src/App.js
On the CSB, clicking any mesh switches colors, when it shouldn't. The code switches between material1 which correctly appears red, and its clone material2, which incorrectly appears white.

Ideally, clone should copy shaders without recompiling them. At a minimum, it should copy with recompile. Currently, it does neither.

**Comment by FarazzShaikh** [comment]
Fixed in `v3.5.0`, does it work now? - https://codesandbox.io/s/transformcontrols-and-makedefault-forked-pgfxr1

**Comment by hamzakubba** [comment]
Thank you so much! Seems to work in the CSB, will try to repro with something more substantial to test it out further.
