### ISSUE TITLE
Fresnel effect example

### ISSUE THREAD

**Issue by marcelpi** [FarazzShaikh/THREE-CustomShaderMaterial#21]
Hi there,

Sorry for posting this as an issue, but I've been trying to create a Fresnel effect on a mesh and didn't manage to accomplish anything. So, I'm trying not to waste any more hours.

Does anyone have an example of how I can add the **Fresnel using CustomShaderMaterial?**

My current code is this:

```
<mesh position={[15, 0, 0]}>
    <sphereGeometry args={[5, 100, 100]} />
    <CustomShaderMaterial
        baseMaterial={THREE.MeshPhysicalMaterial}
        color={'#612700'}
        vertexShader={`
            varying vec3 vPositionW;
            varying vec3 vNormalW;
            void main() {
                vPositionW = normalize(vec3(modelViewMatrix * vec4(position, 1.0)).xyz);
                vNormalW = normalize(normalMatrix * normal);
                gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
            }
        `}
        fragmentShader={`
            varying vec3 vPositionW;
            varying vec3 vNormalW;
            void main() {   
                float fresnelTerm = ( 1.0 - -min(dot(vPositionW, normalize(vNormalW) ), 0.0) );    
                gl_FragColor = vec4(1.0,0.0,0.0,1.0) * fresnelTerm;
            }
        `}
        roughness={0.65}
        reflectivity={1}
    />
</mesh>
```

But it doesn't have any effect.
Any help would be greatly appreciated since this has been driving me crazy.

Thank you.

**Comment by FarazzShaikh** [comment]
Hey! Thanks for using the library! You must use the special output variables provied by CSM for it to take effect. Here you go https://codesandbox.io/s/interesting-oskar-8153vp?file=/src/App.js:1012-1101

**Comment by marcelpi** [comment]
> Hey! Thanks for using the library! You must use the special output variables provied by CSM for it to take effect. Here you go https://codesandbox.io/s/interesting-oskar-8153vp?file=/src/App.js:1012-1101
> 
> Refer to the readme for what these variables are

Thanks so much for this, problem solved.
Really good work on the libraray, I appreciate it. <3
