### ISSUE TITLE
ERROR: 0:645: 'csm_Normal' undeclared identifier

### ISSUE THREAD

**Issue by Wambosa** [FarazzShaikh/THREE-CustomShaderMaterial#22]
Version 3.5.3 throws shader compilation errors with lamina.

![image](https://user-images.githubusercontent.com/6006222/182025680-f16d750f-eaaf-471a-a04c-c58913055122.png)

```
ERROR: 0:645: 'csm_Normal' : undeclared identifier
ERROR: 0:645: 'assign' : l-value required (can't modify a const)
ERROR: 0:645: '=' : dimension mismatch
ERROR: 0:645: 'assign' : cannot convert from 'highp 3-component vector of float' to 'const highp float'
```

Excellent work on this lib by the way!
I humbly recommend following semvar to the letter if you've got inter dependencies between your own libs like this one and lumina.
I mention this only because I read you here:

> I like to keep breaking changes to minor releases.
per https://github.com/pmndrs/lamina/issues/38#issuecomment-1159628947

Be very careful with this approach. Any breaking changes should change the major version for your own sake. The package managers have built-in support for semvar, but will not support a new paradigm that looks like semvar _(in moving breaking changes from major to minor, people may be caught unawares, even you the creator!!; perhaps the life you save can be your own <3)_.

**Comment by FarazzShaikh** [comment]
Hey! Thanks for all the kindness! And yikes, thaks for the tip, going to be following semver from now, breaking changes will require a major version. The shader bug you mention has been fixed in `4.0.0`
