### ISSUE TITLE
Override fragment normals?

### ISSUE THREAD

**Issue by nwpointer** [FarazzShaikh/THREE-CustomShaderMaterial#23]
Would be nice to override normals in the fragment shader as well.

In the custom shader I was trying to port over to CSM I sample one or more normal maps and blend them together: 

<img width="940" alt="Screen Shot 2022-08-14 at 1 32 04 PM" src="https://user-images.githubusercontent.com/3927051/184553904-8549413e-9b12-4b52-a1d4-c32cd7c3e62f.png">

more specifically updating the variable mapN or Normal is what I care about I guess: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normal_fragment_maps.glsl.js#L23 
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normal_fragment_maps.glsl.js#L28

**Comment by nwpointer** [comment]
I think I figurer out how to use patchMap for this

**Comment by FarazzShaikh** [comment]
Yes patchMaps is the way to go for custom overrides, let me know if you need help with that.

 Else let’s close this if you’ve figured it out, also please post the solution if you don’t mind so other can benefit too!

**Comment by nwpointer** [comment]
ok! will post my solution once I've got it working :) 

thanks for confirming this is the way forward.

**Comment by nwpointer** [comment]
ok so here's the hello world for modifying normal maps. This basically is a simplified version of what  the default shaders do when you set provide a normalmap img but the user of the CSM is free to replace the logic in Main() with what ever logic they want as long as it assigns a value to csm_NormalMap.

`<CustomShaderMaterial
      baseMaterial={MeshStandardMaterial}
      map={diffuse[0]}
      normalMap={normal[0]}
      fragmentShader={glsl`
        precision mediump float;
        vec3 csm_NormalMap;
        
        void main(){
          csm_NormalMap = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;
        }
      `}
      patchMap={{
        csm_NormalMap: {
          "#include <normal_fragment_maps>": glsl`
            vec3 mapN = csm_NormalMap;
            mapN.xy *= normalScale;
            normal = perturbNormal2Arb( - vViewPosition, normal, mapN, faceDirection );
          `,
        },
      }}
    />`

**Comment by drone1** [comment]
Does one need to do anything special to use ``perturbNormal2Arb``? I get an error when I try to use this code.

ERROR: 0:1412: 'perturbNormal2Arb' : no matching overloaded function found

Thanks.

**Comment by drone1** [comment]
I forgot to comment again here. The issue was that I set ``normalMap`` after first render, which would cause a shader compilation failure. You gotta set normalMap before first render so that all the right ``#define``'s are in place.

**Comment by nhtoby311** [comment]
@drone1 I'm running into the same issue `'perturbNormal2Arb' : no matching overloaded function found`

> The issue was that I set normalMap after first render, which would cause a shader compilation failure. You gotta set normalMap before first render so that all the right #define's are in place.

I'm not sure how can I send normalMap before first render of the component. Can you tell me how should I modify my code?

```tsx
//MyMesh.tsx
...
const [diffuse, normal] = useTexture(
    [
        '/diffuse.jpg',
        '/normal.jpg',
    ],
    ([diffuse, normal]) => {
        diffuse.flipY = false
        normal.flipY = false

        diffuse.colorSpace = THREE.SRGBColorSpace
        normal.colorSpace = THREE.NoColorSpace
    }
)

return (
   <mesh>
     <CSM
          baseMaterial={MeshStandardMaterial}
          fragmentShader={fragmentShader}
          uniforms={uniforms}
          map={diffuse}
          normalMap={normal}

          patchMap={{
              csm_NormalMap: {
                  '#include <normal_fragment_maps>': `
                  vec3 mapN = csm_NormalMap;
                  mapN.xy *= normalScale;
                  
                  // !!! 'perturbNormal2Arb' : no matching overloaded function found !!!
                  normal = perturbNormal2Arb( - vViewPosition, normal, mapN, faceDirection );
                `,
              },
          }}
      />
   </mesh>
)
```

**Comment by nhtoby311** [comment]
I figured out the issue, it was because since then, three.js normal shader chunk has been changed: https://github.com/mrdoob/three.js/commit/08727dd9e942da5d6fcd6be560735fd478fe43c9#diff-be6360d4dd063b6976dfa19ebfbf3abfe2242e78d67859b83f328df9a079d0d9R26

I changed the patchMap to the following and it seems to work!

```tsx
<CSM
    baseMaterial={MeshStandardMaterial}
    fragmentShader={fragmentShader}
    uniforms={uniforms}
    map={diffuse}
    normalMap={normal}

   patchMap={{
        csm_NormalMap: {
            '#include <normal_fragment_maps>': `
            vec3 mapN = csm_NormalMap;
            mapN.xy *= normalScale;
            normal = normalize( tbn * mapN );
          `,
        },
    }}
/>
```

**Comment by FarazzShaikh** [comment]
Awesome, thanks JS for figuring that out. Fragment normal will be a part of v6 soon
