### ISSUE TITLE
Is it possible to output a normal from a fragment shader?

### ISSUE THREAD

**Issue by drone1** [FarazzShaikh/THREE-CustomShaderMaterial#26]
Hello and thanks for this great software.

I am extending MeshStandardMaterial and would like to output a normal per pixel from my fragment shader but I see that csm_Normal is vertex-shader-only. 

How can I address this? My goal is to build a material that has an animating normal map but leverages all of the lighting and other potential of the standard material.

Please tell me it's possible. Perhaps with patchMap? I do not see docs and I'm on my phone and can't look at the example code easily. 

Thank you!

**Comment by FarazzShaikh** [comment]
Please see #23 as this has already been discussed and solved there

**Comment by drone1** [comment]
Aha! Wonderful news. Thank you so much.
