### ISSUE TITLE
"Multiple instances of Three.js being imported" issue

### ISSUE THREAD

**Issue by dannyWoodford** [FarazzShaikh/THREE-CustomShaderMaterial#27]
Hey I'm using your package in a project I'm working on, great library btw, and I get this warning.  

<img width="603" alt="Screen Shot 2022-09-27 at 4 07 28 PM" src="https://user-images.githubusercontent.com/50857236/192640017-ae2c6a0f-f1b6-4c15-80b1-6767eee22196.png">

I don't know too much about package creation but I think all you have to do to fix it is not export your node_modules along with the npm, I think. At least when I remove the node_modules and reinstall the warning goes away.

<img width="347" alt="Screen Shot 2022-09-27 at 5 37 24 PM" src="https://user-images.githubusercontent.com/50857236/192640945-d8ee8478-91ed-4bae-ab54-0d70c1028334.png">

**Comment by FarazzShaikh** [comment]
What version are you using? This should’ve been fixed long ago

**Comment by FarazzShaikh** [comment]
Please use the latest version - 4.0.0 and see if that fixes it. I cannot guarantee the integrity of outdated versions
