### ISSUE TITLE
Can you disable projection in the vertex shader?

### ISSUE THREAD

**Issue by itsdouges** [FarazzShaikh/THREE-CustomShaderMaterial#28]
Hello! I'm trying to implement a billboard effect for trees (example video of the effect below) and am running into issues with how Three handles custom shaders (in essence: all or nothing!) which makes things way harder than they need to be. Your library looks great but I'm unable to use it currently because of the "projection happening down the line" part. 

https://user-images.githubusercontent.com/6801309/198984210-db7d9874-f4ca-4a4e-98bd-4265af838299.mov

In my vertex shader I project into MV space to then apply the offset. Is it possible to do the projection ourselves?

**Comment by madou** [comment]
Oh! I was digging through source and found `csm_PositionRaw` - seems promising! I can raise a PR to get this added to the README? 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/6801309/198985626-40869220-a3c9-44f7-81cd-15fcade7a62c.png">

**Comment by FarazzShaikh** [comment]
If you find it to be stable then feel free to PR 🙌

**Comment by FarazzShaikh** [comment]
Closing as solved. Will review the PR if you make it!
