### ISSUE TITLE
How to supply the fragment shader uniforms?

### ISSUE THREAD

**Issue by stevejtrettel** [FarazzShaikh/THREE-CustomShaderMaterial#3]
Hi!
After choosing a material (for example here I'll use MeshPhysicalMaterial; as that's my primary use case), it is unclear how to access or supply the usual parameters for that material.  For the built in materials, I would usually specify them at the time of creation such as:

`   new MeshPhysicalMaterial({
            map: myTexture,
            transparent:true,
            clearcoat:1,
            envMap: myEnvMap,
            side: DoubleSide,
        });`

Or, set them afterwards via something like

`material.color.set(0x00FFFF);`

If its helpful - I have found that you may access and modify uniforms of the CustomShaderMaterial via material.unforrms, for example after declaring a material of the type CustomShaderMaterial, and running the following:

```
    material.uniforms.clearcoat.value=1.;
    material.uniforms.opacity.value=0.5;
    material.uniforms.map.value=myTexture;
    console.log(material.uniforms);

```
I see that the uniform values are appropriately updated in the console log.  But then should I use this material in a mesh, none of these changes are visible, so either these are not the correct values for me to be updating, or the updates are not making it to the fragment shader somehow?

UPDATE:
If I follow the above by    
` material.uniformsNeedUpdate=true;`
before creating a mesh with the material, it appears I can indeed change the opacity, but so far nothing else visibly, despite the values in material.uniforms appearing changed.

One thing that leads me to think that I am going about this wrong is that (I think) at the end of the day, as far as THREEJS knows, the material I have made is a ShaderMaterial, so while I could access the map of the actual PhysicalMaterial via

`material.map`

(ie directly, without 'uniforms') trying such a thing on the custom material returns 'undefined'

**Comment by FarazzShaikh** [comment]
Hey! ThreeJS uses options in a specific material object to set shader properties. I think this is done in the form of `#define` constants. 

Since this material uses a regular shader material internally, those options are not available and never get set and the fragment shader never gets told to enable special effects such as an envMap or clearcoat.

I’ll look into this and make this material work with a wider range of effects.

**Comment by FarazzShaikh** [comment]
I have made a patch and pushed it to the `dev` branch. Can you try out your advanced use cases now? The usage should remain similar for the most part, however to update uniforms you now directly refer to them like you do with any other material:
```js
material.uniforms.uTime.value = dt * 0.001;
```

It seems to work with `envMaps` now you can see my example for how I have done it.

<img width="912" alt="Screen Shot 2021-05-14 at 12 24 45 PM" src="https://user-images.githubusercontent.com/55190601/118233327-66afb600-b4af-11eb-9863-71b187388e42.png">

I will test out more advanced use cases before publishing a release

**Comment by stevejtrettel** [comment]
Got it running on my end - but for me at least it appears that the vertex locations are no longer being updated by displace(), though the normals seem to be.

**Comment by FarazzShaikh** [comment]
Can you check if you have the library “glNoise” in the `lib` folder? The example uses this library’a Perlin noise function

Also any errors in the console?

**Comment by stevejtrettel** [comment]
I did not at first (but noticed missing files console errors, and had downloaded it separately from your GitHub; after that I was able to get things running with no errors in the console).  My sphere looks like your example! But the surface is actually smooth, just the texture appears to be warped (looking at the edge of the sphere in your picture, the sphere there kind of looks smooth too?) I'd confirmed by replacing the vertex shader with something simple: starting from a plane material, to push the vertices in the z-direction by a function (here sin(xy)).  You can see from front on-it is updating the direction its getting the envMap from

<img width="774" alt="Screen Shot 2021-05-14 at 08 25 53" src="https://user-images.githubusercontent.com/4812518/118293078-23911b00-b48e-11eb-9a7b-216c8897356e.png">


But, if you look more edge on, you see the surface is actually flat, like the sphere is for me.
<img width="774" alt="Screen Shot 2021-05-14 at 08 26 01" src="https://user-images.githubusercontent.com/4812518/118293192-40c5e980-b48e-11eb-8ccc-78045f3e0960.png">

While the issue happens the same on the sphere I think, here's what's changed in this second example: the geometry is replaced with

`const geometry = new THREE.PlaneGeometry(1,1, 100,100);`

The file 'header.glsl' is replaced with

```
vec3 displace(vec3 p){
    return 10.*vec3(p.x,p.y,sin(10.*3.1415*p.x*p.y));
}

```


And main.glsl is replaced with this:

```
vec3 newPos = displace(position);

float offset = 0.01;
vec3 tangent = vec3(1,0,0);
vec3 bitangent = vec3(0,1,0);
vec3 neighbour1 = position + tangent * offset;
vec3 neighbour2 = position + bitangent * offset;

vec3 displacedNeighbour1 = displace(neighbour1);
vec3 displacedNeighbour2 = displace(neighbour2);

vec3 displacedTangent = displacedNeighbour1 - newPos;
vec3 displacedBitangent = displacedNeighbour2 - newPos;

vec3 newNormal = normalize(cross(displacedTangent, displacedBitangent));

```

**Comment by stevejtrettel** [comment]
Update - I played around some more during breakfast with this and noticed in the defining of the CustomShaderMaterial, if you replace the baseMaterial type from BASIC to PHYSICAL, the vertex displacement is rendered correctly: however the envMap is no longer noticed (here's the change and picture)

```
const material = new CustomShaderMaterial({
    baseMaterial: TYPES.NORMAL,
....
```

<img width="774" alt="Screen Shot 2021-05-14 at 09 01 26" src="https://user-images.githubusercontent.com/4812518/118297675-52f65680-b493-11eb-9cc1-9651f0eb5cc6.png">

Getting no errors in the console here for PHYSICAL or BASIC -but throwing in some of the other types (NORMAL or PHONG) throws errors.

**Comment by FarazzShaikh** [comment]
Yes i found the same. For some reason `BASIC` material does not actually displace the mesh. But setting it to use `PHYSICAL` along with:
```js
passthrough: {
      metalness: 1,
      roughness: 0,
},
```

Makes it displace and reflect the envMap nicely. Im guessing its got something to do with internal parameters of Basic material. 

Also, `PHONG` and `NORMAL` will throw errors when an envMap is assigned to them but work nicely once that line is commented out. I will add some error handing and warnings for these edge cases. 

If you find more bugs please let me know lol, this was immensely helpful, thanks!

**Comment by stevejtrettel** [comment]
Ah yes - I forgot to get rid of the envMap before trying NORMAL: that makes total sense thanks!
And you're right things appear to be working perfectly well for MeshPhysicalMaterial.  
<img width="774" alt="Screen Shot 2021-05-14 at 09 33 23" src="https://user-images.githubusercontent.com/4812518/118301074-84712100-b497-11eb-8660-ec2b8ea1cf62.png">

I'll definitely let you know what else I come across - and will share this weekend some of the math illustrations that this is going to make possible!   Thanks a ton for all the help so far and for making this awesome little project :-)

**Comment by FarazzShaikh** [comment]
Sure, I will close this issue once the fixes are released.

Also, you can share your work in a new issue here and maybe we can use that as examples for the usage of this library. 😄
