### ISSUE TITLE
Warning: Function copy already exists on CSM, renaming to base_copy 

### ISSUE THREAD

**Issue by AxiomeCG** [FarazzShaikh/THREE-CustomShaderMaterial#37]
![image](https://user-images.githubusercontent.com/18304870/234808381-d1e5cf80-1b23-4d82-90e7-abc5383a23f8.png)

I have often this warning in the console, I wonder if there is a way to disable it? 

If not, would you agree to add a `verbose` property that we can set to false that would disable any warning in the console ?

For instance: 

```jsx
<CustomShaderMaterial
              baseMaterial={MeshPhongMaterial}
              uniforms={{}}
              verbose={false}
/>
```

Thank you in advance.

**Comment by FarazzShaikh** [comment]
Yeah I could do that. These warning were a temporary solution till I figured a better way to handle already defined methods. 

I will look into it, thanks for the report!

**Comment by jakobhenner** [comment]
+1 on this request.

Anyway, thank you so much for this package. Been very useful.
