### ISSUE TITLE
Waves example seems to be broken

### ISSUE THREAD

**Issue by gabrieljreed** [FarazzShaikh/THREE-CustomShaderMaterial#40]
The waves example shown in the README seems to be broken: This is the result I see running it on both Firefox and Chrome: 

![image](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/assets/60671652/6cbf3a30-fad4-4e9c-9a85-4f78b55d8f86)

The other examples work fine, just thought you'd want to know that the waves example seems to be down.

**Comment by FarazzShaikh** [comment]
This is a bug related to CodeSandbox where React spring (which is used in Drei) tends to fail. I’ve seen it multiple times across multiple boxes. 

Can you try forking the example and updating the dependencies?

**Comment by gabrieljreed** [comment]
Sorry for the late reply, I built locally and was able to run the example just fine. I'm afraid I don't have much experience with CodeSandbox, so I'm not sure how to help there. I just did the normal install, nothing needed to be updated (I have no changes to the package.json). Let me know if there's anything else I can do to help!

**Comment by FarazzShaikh** [comment]
Thank you’d or your investigation! This seems like problem in react-spring. I will update the dependencies to see if that fixes it, if not then this can’t be fixed here.
