### ISSUE TITLE
Problem with using csm_PositionRaw and InstancedMesh

### ISSUE THREAD

**Issue by ManHunterGroms** [FarazzShaikh/THREE-CustomShaderMaterial#42]
Hello,  @FarazzShaikh, thank you for awsome extension of three.js.

I found a bug with using csm_PositionRaw with InstancedMesh. See screenshots:
### 1) vertex shader:
```glsl 
void main() {
    csm_PositionRaw = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
```
all vertices are set to the zero position
![image](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/assets/4003735/688119f5-4489-4465-ac4b-3274d5122a91)

### 2) vertex shader (empty):
```glsl 
void main() {
}
```
or
```glsl 
void main() {
    csm_Position = position;
}
```
works fine:
![image](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/assets/4003735/76a54a0b-6fa1-4975-b23a-d51d9a363025)

**Comment by FarazzShaikh** [comment]
`csm_PositionRaw` is the same as `gl_Position` thus, to use it with InstancedMesh, you need to multiply the position with the `instanceMatrix` before projection
```glsl
csm_PositionRaw = projectionMatrix * modelViewMatrix * instanceMatrix * vec4(position, 1.0);
```

Let me know if this fixes your issue

`csm_Position` is the prefered way to override vertex position as you dont need to project or multiply the `instanceMatrix` to it, it is done for you.

**Comment by FarazzShaikh** [comment]
What is your baseMaterial?

**Comment by FarazzShaikh** [comment]
Here: https://codesandbox.io/s/wizardly-neco-hczrcn?file=/src/App.tsx:869-976

It seems to work just fine. In my sandbox. Toggling "instanceMesh" in the controls will toggle the multiplication of the matrix.

**Comment by ManHunterGroms** [comment]
@FarazzShaikh yeah, sorry for delay, I never used the sandbox)
My sandbox is working fine... strange.
https://codesandbox.io/s/kind-vaughan-thjnch?file=/src/index.js

ok, I will search and fix the error in my project.
Thank you so much for support.

Please do not close the Issue, later I will answer what the problem was 😀

**Comment by ManHunterGroms** [comment]
Found the cause of the problem, I will used the material not only in InstancedMesh 🤦‍♂️

**Comment by FarazzShaikh** [comment]
What was the solution?

**Comment by ManHunterGroms** [comment]
> What was the solution?

Use ```USE_INSTANCING``` preprocessor directive.
```glsl
   #ifdef USE_INSTANCING
        vec4 vertexWorldPosition = modelViewMatrix * instanceMatrix * vec4(position, 1.0);
   #else
        vec4 vertexWorldPosition = modelViewMatrix * vec4(position, 1.0);
    #endif
 ```

**Comment by FarazzShaikh** [comment]
Ahh yes, instanceMatrix is not available if not used with InstancedMesh. Glad it’s solved 😄
