### ISSUE TITLE
TresJs implementation

### ISSUE THREAD

**Issue by JaimeTorrealba** [FarazzShaikh/THREE-CustomShaderMaterial#43]
Hi! would you accept a PR,  to contain the implementation for using CSM with TresJs?

[TresJs](https://github.com/Tresjs) is the R3F of Vue.

I have already playing with your library but using the vainilla version [example](https://lab.jaimetorrealba.com/CSMDemo)
The import will do like:
import CustomShaderMaterial from 'three-custom-shader-material/tresjs' (or similar)

And you can also be use easily with the Vue 3D comunity :)

**Comment by FarazzShaikh** [comment]
Of course, go for it! 

The only issue is I dont use Vue, so the view bit might go unmaintained, unless youre willing to commit to maintaining it. Nonetheless, it'll definitely be useful 😄

**Comment by JaimeTorrealba** [comment]
Thanks :).

I'll work in a solution and send you the PR for feedback.
And yes I'll maintain this one, No problem
