### ISSUE TITLE
How to change the opacity of extended material ?

### ISSUE THREAD

**Issue by TheoGil** [FarazzShaikh/THREE-CustomShaderMaterial#44]
Hello

I would like to change only the alpha component of final color but cannot figure out how to do so. 

Is this something that is currently easily feasible ?

To illustrate what I'm trying to achieve, here's to different pseudo-code solutions that would both satisfy my use case.

```glsl
// In this pseudo-code example, the (imaginary) csm_Alpha is used to set the final gl_FragColor alpha component
void main() {
    csm_Alpha = 0.5;
}

// In this other pseudo-code example, I am able to retrieve the "temporary color" and update its alpha component.
// The cms_TemporaryColor is not a "real property", here it would hold the color value as set by the extended material, before any CSM modification.
void main() {
    csm_DiffuseColor = vec4(cms_TemporaryColor.r, cms_TemporaryColor.g, cms_TemporaryColor.b, 0.5);
}
```

Using the Material's `opacity` property is not a viable option in my case because I am working with an InstancedBufferGeometry and would like every instance to have a different alpha value.

Thanks!

**Comment by FarazzShaikh** [comment]
Yes, `csm_DiffuseColor` is preloaded with the materials `color` prop. However, for InstancedMesh, you need to pass the color as a varying or use the pre-existing `vColor` varying like so: 

```glsl
#ifdef USE_INSTANCING_COLOR
    csm_DiffuseColor.rgb = vColor;
#endif
csm_DiffuseColor.a = 0.5;
```

https://codesandbox.io/s/async-rain-2qw5tx?file=/src/App.tsx:909-954

**Comment by TheoGil** [comment]
Awesome, thank you @FarazzShaikh for the precision
