### ISSUE TITLE
Failed to resolve module specifier "crypto"

### ISSUE THREAD

**Issue by Criska9527** [FarazzShaikh/THREE-CustomShaderMaterial#51]
I get this error after importing, what's going on, I don't have crypto in my project

 error message：Failed to resolve module specifier "crypto"

version：three-custom-shader-material 5.3.8

**Comment by FarazzShaikh** [comment]
This comes from the `object-hash` library used if your framework doesn’t have a polyfill for th NodeJS package `crypto`

it’s a bug. Will be fixed with the release of v6 this week
