### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by mrdoob** [FarazzShaikh/THREE-CustomShaderMaterial#54]
Was checking out the project and noticed that a couple of the examples seemed to be broken?

* Hero (Macbook Pro M1 Pro)

https://codesandbox.io/s/github/FarazzShaikh/THREE-CustomShaderMaterial/tree/main/examples/hero 

![Screenshot 2024-05-27 at 3 34 09 PM](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/assets/97088/5bfad680-49a7-477d-96cd-23f9a114a575)

* Waves

https://codesandbox.io/s/github/FarazzShaikh/THREE-CustomShaderMaterial/tree/main/examples/waves

![Screenshot 2024-05-27 at 3 31 40 PM](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/assets/97088/f02fa7be-17df-43de-a033-99d68e4aec1c)

**Comment by FarazzShaikh** [comment]
Hey! Thanks for the heads up. Yep I’m working on new releases (currently in the v6 branch) that should fix these and make the library more compact. 

Haven’t had much time but wanting to get it across the line soon

**Comment by mrdoob** [comment]
Ah! Okay 👌

**Comment by FarazzShaikh** [comment]
Thanks for checking it out! Let me know if you have any other Qs 😄
