### ISSUE TITLE
examples for mapping color attribute? (never been done…)

### ISSUE THREAD

**Issue by rohanrehman** [FarazzShaikh/THREE-CustomShaderMaterial#55]
I have a use case that suprisingly nobody has attempted.

maybe you can do an example that loads a Ply file (most compact file format if working with clouds with color data ). And leverage your custom shader to map the color data from the geometry.attributes.

you will find the method of using a vector shaders DataTexture to save and compute positions.

one can morph and animate a point cloud that has the same geometry of what you’ve loaded.

but nobody has successfully mapped the color data of those vertexes onto the fragment shader.

using Points and PointMaterial is an easy method to achieve it but PointMaterial does not leverage GPGPU.

**Comment by FarazzShaikh** [comment]
I am unsure what this means but sounds like out of the scope of this library. This library will be archived after the full release of ThreeJS NodeMaterial, so I do not plan on making any large addition to its feature set.
