### ISSUE TITLE
Losing reflectivity of Physical Material.

### ISSUE THREAD

**Issue by Jbmanllr** [FarazzShaikh/THREE-CustomShaderMaterial#56]
Hello, im losing reflectivity of physical material when extending it: 

`   <CustomShaderMaterial
              ref={materialRef}
              baseMaterial={THREE.MeshPhysicalMaterial}
              //vertexShader={vertex}
              //fragmentShader={fragment}
              silent
              //uniforms={materialUniforms}
              {...options}
            />·`
Sorry, to be more specific, and after tests, reflectivity works, but is not controllable dynamically eg with leva like other props.

**Comment by FarazzShaikh** [comment]
Please provide some more details about your I pimentos. Some code would be helpful. “Reflectivity” is not a material parameter, you can control Roughness or Metalness which would affect the reflectivity 

Please re-open with more details
