### ISSUE TITLE
Access to custom normal map

### ISSUE THREAD

**Issue by nhtoby311** [FarazzShaikh/THREE-CustomShaderMaterial#58]
I'm trying to create a shader transition between different PBR texture materials, and I managed to do it with Diffuse, Rougness and Metalness map! However, according to the [docs](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial?tab=readme-ov-file#output-variables), there is no custom normal for normal map. Is there a possible way to have access to the normal map?

**Comment by FarazzShaikh** [comment]
This is a highly requested feature and will be a part of the new v6 release. Meanwhile, you can use the patch map described here. Let me know if it works!

https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/issues/23#issuecomment-1217284749

**Comment by nhtoby311** [comment]
Thank you! I tried the code in the issue, and ran into an error with it, so I leave a comment there.

Looking forward for the v6!
