### ISSUE TITLE
Example use: Complex Function Grapher

### ISSUE THREAD

**Issue by stevejtrettel** [FarazzShaikh/THREE-CustomShaderMaterial#6]
Not an issue but an example  putting the custom shader material to use (I think this is where you said to post it still?).  Starting with PlaneGeometry, rewrite the vertex shader to map points to a parametric surface (here, a projection to R3 of the graph of some complex polynomials in R4).  
The result is then textured using a fragment shader  whose output is used as the map: on a MeshPhysicalMaterial.

<img width="646" alt="Screen Shot 2021-05-15 at 10 53 32" src="https://user-images.githubusercontent.com/4812518/118373579-8eb11f00-b56c-11eb-92f9-437dc215836a.png">
<img width="646" alt="Screen Shot 2021-05-15 at 10 54 05" src="https://user-images.githubusercontent.com/4812518/118373581-91137900-b56c-11eb-9d3a-61acb68ed87c.png">

<img width="738" alt="Screen Shot 2021-05-15 at 10 59 37" src="https://user-images.githubusercontent.com/4812518/118373600-a9839380-b56c-11eb-9b84-bbccfd7a5f6c.png">

As a comparison with a similar program I wrote doing this with THREE.ParametricGeometry (re-creating the geometry when the function changes), CustomShaderMaterial let me subdivide the domain 100x finer, at which point the result was still running 4x faster (60fps) than my original version.

**Comment by FarazzShaikh** [comment]
That’s so cool! Do you have the code for this? 

Can you fork this repo and add the code to a separate directory in the examples folder? 

Update me here once it’s done, I’ll integrate it into the demo site then we can merge it into this repo!

**Comment by stevejtrettel** [comment]
Done!

**Comment by FarazzShaikh** [comment]
Can you make a PR into the dev branch?

**Comment by FarazzShaikh** [comment]
Closed by #8. If you have any more examples, would love to see them! Create a PR and they will be merged. Also feel free to edit your examples to include a little description for the uninitiated. 

Thank you very much! 😄

**Comment by stevejtrettel** [comment]
Sounds good! Later this week when I have some time I'll add a description and throw send over the next example when its done.  Here's the start to it! 
<img width="950" alt="Screen Shot 2021-05-16 at 22 34 37" src="https://user-images.githubusercontent.com/4812518/118518821-5dac2800-b6ed-11eb-906a-3784b79a091e.png">

**Comment by FarazzShaikh** [comment]
Looking forward to it!
