### ISSUE TITLE
`csm_FragNormal` gives incorrect normal results

### ISSUE THREAD

**Issue by nhtoby311** [FarazzShaikh/THREE-CustomShaderMaterial#61]
It looks like the `csm_FragNormal` might gives normal to the view position, instead of world position. 

I have created CSB for this issue: https://codesandbox.io/p/sandbox/z9wspj?file=%2Fsrc%2FScene.tsx%3A12%2C15

In the CSB, the "left" one is the one use `csm_FragNormal`, "center" is just .glb using its materials, and "right" is the `patchMap: csm_NormalMap` approach. When you rotate around, the "left" gives changing light issue.

![image](https://github.com/user-attachments/assets/6d287d54-9f01-4f80-888c-998cce35ab9c)

**Comment by FarazzShaikh** [comment]
Hello, seems like the CSB is private. I'm unable to see it

If using a normal map via uniforms, `csm_FragNormal` needs to be furthur processed depending on if your normal map is in Object or Tangent space. You can see the processing ThreeJS does here: 

https://github.com/mrdoob/three.js/blob/a8b6c17696d5cbc001ba9f7685a93cee9ddb0018/src/renderers/shaders/ShaderChunk/normal_fragment_maps.glsl.js#L3-L26

Try using the following code and let me know if it works

```glsl
mat3 getTangentFrame( vec3 eye_pos, vec3 surf_norm, vec2 uv ) {
  vec3 q0 = dFdx( eye_pos.xyz );
  vec3 q1 = dFdy( eye_pos.xyz );
  vec2 st0 = dFdx( uv.st );
  vec2 st1 = dFdy( uv.st );
  vec3 N = surf_norm;
  vec3 q1perp = cross( q1, N );
  vec3 q0perp = cross( N, q0 );
  vec3 T = q1perp * st0.x + q0perp * st1.x;
  vec3 B = q1perp * st0.y + q0perp * st1.y;
  float det = max( dot( T, T ), dot( B, B ) );
  float scale = ( det == 0.0 ) ? 0.0 : inversesqrt( det );
  return mat3( T * scale, B * scale, N );
}

void main() {
  ...
  mat3 tbn = getTangentFrame(-vViewPosition, vNormal, vUv);
  csm_FragNormal = normalize(tbn * yourNormal);
```

This is left in user-land because unlike ThreeJS, CSM does not have knowlage of your Normal Map configuration since it is provided as an external uniform. Users may also be using procedural normals. 

I will add this "gotcha" to the readme

**Comment by nhtoby311** [comment]
Thanks for the help! I have updated the CSM and also public it again. It's working now!

I also need to rename the functions `getTangentFrame` and `tbn` to avoid compile error, as they are used in the base material.

```tsx
<CSM
  baseMaterial={MeshStandardMaterial}
  fragmentShader={`
  uniform sampler2D uDOne;
  uniform sampler2D uNOne;

  mat3 getTangentFrameCustom( vec3 eye_pos, vec3 surf_norm, vec2 uv ) {
    vec3 q0 = dFdx( eye_pos.xyz );
    vec3 q1 = dFdy( eye_pos.xyz );
    vec2 st0 = dFdx( uv.st );
    vec2 st1 = dFdy( uv.st );
    vec3 N = surf_norm;
    vec3 q1perp = cross( q1, N );
    vec3 q0perp = cross( N, q0 );
    vec3 T = q1perp * st0.x + q0perp * st1.x;
    vec3 B = q1perp * st0.y + q0perp * st1.y;
    float det = max( dot( T, T ), dot( B, B ) );
    float scale = ( det == 0.0 ) ? 0.0 : inversesqrt( det );
    return mat3( T * scale, B * scale, N );
  }

  void main() {
    vec4 diffuseMapGreen = texture2D(uDOne, vMapUv);
    vec3 normalMapGreen = texture2D(uNOne, vNormalMapUv).xyz * 2.0 - 1.0;

    mat3 tbnCustom = getTangentFrameCustom(-vViewPosition, vNormal, vNormalMapUv);
    csm_DiffuseColor = diffuseMapGreen;
    csm_FragNormal = normalize(tbnCustom * normalMapGreen);
  }
  `}
  uniforms={uniforms}
  ref={materialRef}
  map={diffuse}
  normalMap={normal}
  metalness={0.5}
/>
```

**Comment by FarazzShaikh** [comment]
Great! Your complie errors are beause you are setting `normalMap={normal}` which appends its associated `#include` statements which ultimately addes in a second copy of the `getTangentFrame` function. 

If you are not using the assigned normal map (`normalMap={normal}`), it should be safe to remove that line. Or if you are, then you dont need to re-define the `getTangentFrame` function as it'll already be appended to your shader

**Comment by nhtoby311** [comment]
Thanks for the explanation! I wonder in my case, since I also don't need the diffuse map `map={diffuse}`, and I want to remove it, but then I won't have `vMapUv` as I'm using now, and there is no `vUv` defined if I'm trying to use it. Is there a solution for this, or I should use at least a texture map, so I have the varrying UV?

**Comment by FarazzShaikh** [comment]
You can pass over `vUv` yourself from the vertex shader

```glsl
// vs
varying vec2 vUv;

void main() {
  vUv = uv;
}

// fs
varying vec2 vUv;

void main() {
  vec4 foo = texture(bar, vUv);
}
```

Of course, you'd need to use a different name if you'd like to use both a diffuse input and define your own `vUv`
