### ISSUE TITLE
Examples are broken on r170

### ISSUE THREAD

**Issue by wrangelvid** [FarazzShaikh/THREE-CustomShaderMaterial#64]
I ran into an issue with r170 with type errors in syncing the [uniforms](https://stackblitz.com/edit/vitejs-vite-wsnrxd?file=src%2FApp.tsx). I did see that you recently updated to 170 an the examples [waves](https://farazzshaikh.github.io/THREE-CustomShaderMaterial/#/waves), [points](https://farazzshaikh.github.io/THREE-CustomShaderMaterial/#/points) are broken ...

**Comment by FarazzShaikh** [comment]
It is this line exactly that caused the break: 

https://github.com/mrdoob/three.js/blame/841ca14e89f3ec925e071a321958e49a883343c0/src/materials/Material.js#L22

Introduced by this commit:

https://github.com/mrdoob/three.js/commit/ac963e25c6ddf9ea1f5f070e90e78529db96f701#diff-4081cb9cffbf3263819b3e910698bdd58231bf0ddbda61dd527fec68750d3ea3R22

Basically, threejs decides what default uniforms to give to a material based off the `type`, so, to make a CSM paterial transparent to ThreeJS, we need to override this type.

**Comment by FarazzShaikh** [comment]
Fixed with `6.1.1`, please confirm

**Comment by wrangelvid** [comment]
That fixed it, thank you for the quick attention!
