### ISSUE TITLE
Using MeshTransmissionMaterial causes shader compiling error

### ISSUE THREAD

**Issue by tonyblu331** [FarazzShaikh/THREE-CustomShaderMaterial#65]
Hello,

I am trying to use the MTM with the CSM, but it gives error whenever I try to use them in conjunction. It works fine with THREE.MeshPhysicalMaterial property but not when using drei's MTM.

Here is my code: 

``` 

import CustomShaderMaterial from 'three-custom-shader-material'
import { MeshTransmissionMaterial } from '@react-three/drei'

return (
    <instancedMesh
      ref={meshRef}
      args={[geometry, undefined, gridSize * gridSize]}
      castShadow
      receiveShadow
    >
      <CustomShaderMaterial
        ref={materialRef}
        baseMaterial={MeshTransmissionMaterial}
        uniforms={uniforms}
        vertexShader={`
          varying vec2 vUv;
          
          void main() {
            vUv = uv;
            csm_Position = position;
          }
        `}
        fragmentShader={`
          varying vec2 vUv;
          uniform float uTime;
          
          void main() {
            vec3 color = vec3(vUv.x, vUv.y, sin(uTime));
            csm_DiffuseColor = vec4(color, 1.0);
          }
        `}
        transmission={1}
        thickness={0.5}
        roughness={0.2}
        metalness={0.1}
        clearcoat={0.5}
        clearcoatRoughness={0.2}
        ior={1.5}
      />
    </instancedMesh>
  )
} 
```

and the error I get from Chrome console log:

```
Material Name: CustomShaderMaterial&lt;undefined&gt;
Material Type: Material

Program Info Log: Vertex shader is not compiled.
VERTEX
ERROR: 0:130: 'vUv' : redefinition

  125:     float csm_DepthAlpha;
  126: #endif
  127: 
  128:   
  129:           
&gt; 130:           varying vec2 vUv;
  131:           
  132:           
  133:           
  134:           void main() {
  135:             {
  136:               
FRAGMENT

ERROR: 0:132: 'vUv' : redefinition
ERROR: 0:133: 'uTime' : redefinition
ERROR: 0:246: 'color' : redefinition


  127:     float csm_DepthAlpha;
  128: #endif
  129: 
  130:   
  131:           
&gt; 132:           varying vec2 vUv;
  133:           uniform float uTime;
  134:           
```

**Comment by FarazzShaikh** [comment]
As mentioned in [the readmes’s “Gotchas” section, point number 3](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial?tab=readme-ov-file#gotchas) your varyings, uniforms and keywords are not scoped to your custom shader, this means that if the base material uses the same identifiers, then you will get redefinition errors 

please rename the redefined variables or add a unique prefix/suffix to make them unique

**Comment by tonyblu331** [comment]
I am still facing shaders compiling issues, redefinitions one:

```
  return (
    <instancedMesh
      ref={meshRef}
      args={[geometry, undefined, gridSize * gridSize]}
      castShadow
      receiveShadow
    >
      <CustomShaderMaterial
        ref={materialRef}
        baseMaterial={MeshTransmissionMaterial}
        vertexShader={`
          varying vec2 v_gc_uv;
          
          void main() {
            v_gc_uv = uv;
            csm_Position = position;
          }
        `}
        fragmentShader={`
          varying vec2 v_gc_uv;
          
          void main() {
            vec3 color = vec3(v_gc_uv.x, v_gc_uv.y, 0.5);
            csm_DiffuseColor = vec4(color, 1.0);
          }
        `}
        transmission={1}
        thickness={0.5}
        roughness={0.2}
        metalness={0.1}
        clearcoat={0.5}
        clearcoatRoughness={0.2}
        ior={1.5}
      />
    </instancedMesh>
```

```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Material Name: CustomShaderMaterial&lt;undefined&gt;
Material Type: Material

Program Info Log: Vertex shader is not compiled.

VERTEX

ERROR: 0:130: 'v_gc_uv' : redefinition


  125:     float csm_DepthAlpha;
  126: #endif
  127: 
  128:   
  129:           
&gt; 130:           varying vec2 v_gc_uv;
  131:           
  132:           
  133:           
  134:           void main() {
  135:             {
  136:               
FRAGMENT

ERROR: 0:131: 'v_gc_uv' : redefinition
ERROR: 0:244: 'color' : redefinition


  126:     float csm_DepthAlpha;
  127: #endif
  128: 
  129:   
  130:           
&gt; 131:           varying vec2 v_gc_uv;
  132:           
  133:           
  134:           
  135:           void main() {
  136:             {
  137:               
```

**Comment by FarazzShaikh** [comment]
Where is MTM coming from? Which library? Could you point me to the source so i can test? 

Support for third party materials that use `onBeforeCompile` was dropped from v6 as its not possible to predict the changes made by said materials to the shader chunks. The shader chunks in their "stock" form are vital to the way CSM operates

Third party material may or may not work as stated in [Gotcha #4](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial?tab=readme-ov-file#gotchas). 

However, this may be a bug with CSM's injection code so I will look into it if you can provide me with a CSB or source for MTM

**Comment by FarazzShaikh** [comment]
Also, more pressingly, DREI only exports a React component `MeshTransmissionMaterial` but CSM's base material needs a Vanilla material class

Please try using vanilla MTM and let me know if the problem persistes

**Comment by tonyblu331** [comment]
I am not aware of a vainilla MTM, perhaps the closest will be using MPM and tranmission. As I mentioned when I opened the issues it does work with vanilla materials such as Three.MeshPhysicalMaterial. 

So I guess I can't use Drei along CSM? Any suggested alternative. I just prefer how MTM from Drei looked, but I am aware how much does CSM extends and its capabilities.

**Comment by FarazzShaikh** [comment]
No you can’t use Drei’s MTM out of the box. You can go into Drei’s source and copy out the vanilla MTM implementation. 

Ether way, try it out but as mentioned, it may or may not work. 

If you really want to, you can fork this repo and make it work by patching CSM’s source code. But it probably won’t be possible to make a general solution for all third party materials 

and if you’re doing that then you should simply forgo CSM all together and patch MTM’s source code directly 😅

**Comment by tonyblu331** [comment]
I tried with the drei-vainilla MTM implementation and no luck.. 

```
import CustomShaderMaterial from "three-custom-shader-material/vanilla"
import { MeshTransmissionMaterial } from '@pmndrs/vanilla'

  return (
    <instancedMesh
      ref={meshRef}
      args={[geometry, undefined, gridSize * gridSize]}
      castShadow
      receiveShadow
    >
      <primitive
        object={new CustomShaderMaterial({
          baseMaterial: MeshTransmissionMaterial,
          fragmentShader: /* glsl */ `
            void main() {
              vec4 baseColor = vec4(0.98, 0.98, 0.98, 1.0);

              csm_DiffuseColor = baseColor;
            }
          `,
          uniforms: {},
          _transmission: 0,
          thickness: 0,
          roughness: 0.8,
          chromaticAberration: 0.2,
        })}
      />
    </instancedMesh>
```
    
```
  App.tsx:31 THREE.WebGLProgram: Shader Error 1282 - VALIDATE_STATUS false

Material Name: CustomShaderMaterial<MeshPhysicalMaterial>
Material Type: MeshPhysicalMaterial

Program Info Log: Fragment shader is not compiled.

ERROR: 0:1611: 'transmission' : undeclared identifier
```

I saw an old codesandbox using MTM and CSM but I guess that was an old version, of CSM.

**Comment by FarazzShaikh** [comment]
@pmndrs/vanilla impl does not include all the [frame buffer stuff](https://github.com/pmndrs/drei/blob/da21df304bd275f56c760b588f7852278f098219/src/core/MeshTransmissionMaterial.tsx#L416) that needs to be done to get correct results

> I saw an old codesandbox using MTM and CSM but I guess that was an old version, of CSM.

That is correct, third party materal support was dropped in v6. Feel free to downgrade to v5 and follow that CSB. 

That being said, I am closing this issue as it is out of scope of CSM.
