### ISSUE TITLE
Library use case?

### ISSUE THREAD

**Issue by Danilkat** [FarazzShaikh/THREE-CustomShaderMaterial#67]
TSIA. 
Is it intended for someone that doesnt know threejs' ShaderMaterial interface and usage? Or is it for someone who is fed up with boilerplate code that needed to be written in the Raw/ShaderMaterial's extended class?

I would appreciate if someone would add the `Purpose` section in README

**Comment by FarazzShaikh** [comment]
It is intended to make extending the base material set easier. With CSM no/very little pre-requisite knowledge about internal shader chunk systems needed. 

Without CSM, users would have to know exactly which shader chunk controls which properties of the base material. With CSM, you simply assign the property to an out put variable and the rest is taken care for them.
