### ISSUE TITLE
Preview site has something wrong?

### ISSUE THREAD

**Issue by Siricee** [FarazzShaikh/THREE-CustomShaderMaterial#71]
The preview site has something wrong, while I'm a new learner that I can't fix it.

```
Unexpected Application Error!
Cannot read properties of null (reading '_currentValue')
```

**Comment by FarazzShaikh** [comment]
Strange, the deployed demo site works just fine. What demo exactly is giving you a problem?

**Comment by Siricee** [comment]
Ohhh, that's my mistake...I used tampermonkey plugin on my broswer. The demo site works fine.
